version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
    networks:
      - esnet
    depends_on:
      - mongodb
      - elasticsearch
  mongodb:
    image: "mongo:5.0.6"
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pokemon
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
